name: mobx_effective_architecture
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: ^3.0.8
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.2+5
  flutter_dotenv: ^2.1.0
  flutter_mobx: ^1.0.1
  get: ^1.9.2
  get_it: ^3.1.0
  hive: ^1.4.0+1
  hive_flutter: ^0.3.0+1
  json_annotation: ^3.0.1
  mobx: ^1.0.2
  modal_progress_hud: ^0.1.3
  oktoast: ^2.3.1
  path_provider: ^1.6.0

dev_dependencies:
  mobx_codegen: ^1.0.2
  build_runner: ^1.7.4
  hive_generator: ^0.7.0
  lint: ^1.1.1
  json_serializable: ^3.2.5
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - .env